import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Canonical Stitch Palette (Project 215239094039483739)
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#723600",
        "primary": "#003178",
        "surface-tint": "#2b5bb5",
        "background": "#faf8ff",
        "on-surface": "#131b2e",
        "on-primary-fixed-variant": "#00429c",
        "outline-variant": "#c3c6d4",
        "on-secondary-fixed": "#311300",
        "on-primary-container": "#a1bbff",
        "tertiary-fixed": "#cce5ff",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed-dim": "#ffb786",
        "surface-bright": "#faf8ff",
        "secondary-container": "#fc820c",
        "error-container": "#ffdad6",
        "outline": "#737783",
        "error": "#ba1a1a",
        "tertiary-container": "#00507b",
        "on-primary-fixed": "#001945",
        "secondary": "#964900",
        "primary-fixed": "#d9e2ff",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b0c6ff",
        "primary-fixed-dim": "#b0c6ff",
        "surface": "#faf8ff",
        "surface-container": "#eaedff",
        "on-tertiary-fixed-variant": "#004c6b",
        "on-secondary-container": "#5e2c00",
        "on-tertiary-fixed": "#001d31",
        "surface-variant": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#434652",
        "on-error": "#ffffff",
        "inverse-surface": "#283044",
        "on-background": "#131b2e",
        "surface-dim": "#d2d9f4",
        "surface-container-low": "#f2f3ff",
        "primary-container": "#0d47a1",
        "tertiary-fixed-dim": "#93ccff",
        "tertiary": "#003858",
        "on-tertiary-container": "#7bc3ff",
        "secondary-fixed": "#ffdcc6",

        // Compatibility aliases for existing non-migrated code
        brand: {
          50: "#e3f2fd",
          100: "#bbdefb",
          500: "#1976d2",
          700: "#0d47a1",
          800: "#003178",
          900: "#002041",
        },
        accent: {
          50: "#fff3e0",
          100: "#ffdcc6",
          500: "#fc820c",
          600: "#e65100",
          700: "#964900",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "2.5rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
      },
      fontFamily: {
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-regular": ["'Plus Jakarta Sans'", "sans-serif"],
        "micro-badge": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-semibold": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        caption: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "36px", fontWeight: "700" }],
        display: ["36px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-regular": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "micro-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-semibold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
